version: '3'

services:
  app:
    build: .
    ports:
      - '3000:3000'
      - '5555:5555'
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    # instead of using image bitnami/mongodb:5.0.17 (it's not working), this image builds a replicaset in its own Dockerfile
    build: ./mongo_rs
    restart: always
    environment:
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_REPLICA_HOST: db
      MONGODB_DATABASE: nest
